import type { Metadata } from "next";
import { Victor_Mono } from "next/font/google";

import "../globals.css";
import Navbar from "@/components/Navbar";

const victorMono = Victor_Mono({
    variable : "--font-victor-mono",
    subsets : ["latin"],
    display : 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${victorMono.variable} antialiased pt-20 `}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
